## [5장] 문제 발생에 대비하기
---

<br>

### 5.1 빠른 실패
---
- 메서드가 **빠르게 실패하도록 만든다**
  - **검증 부분을 먼저 위치시킨다**
  - 메서드에서 가장 중요한 부분인 일반적인 경로로 바로 넘어갈 수 있기 때문에, 전체를 읽고 이해하기가 쉽다

```java
// problem
class CruiseControl {
    static final double SPEED_OF_LIGHT_KMH = 1079252850;
    static final double SPEED_LIMIT = SPEED_OF_LIGHT_KMH;

    private double targetSpeedKmh;

    void setTargetSpeedKmh(double speedKmh) {
        if (speedKmh < 0) {
            throw new IllegalArgumentException();
        } else if (speedKmh <= SPEED_LIMIT) {
            targetSpeedKmh = speedKmh;
        } else {
            throw new IllegalArgumentException();
        }
    }
}
```

```java
// solution
class CruiseControl {
    static final double SPEED_OF_LIGHT_KMH = 1079252850;
    static final double SPEED_LIMIT = SPEED_OF_LIGHT_KMH;

    private double targetSpeedKmh;

    void setTargetSpeedKmh(double speedKmh) {
        if (speedKmh < 0 || speedKmh > SPEED_LIMIT) {
            throw new IllegalArgumentException();
        }

        targetSpeedKmh = speedKmh;
    }
}
```


<br>

### 5.2 항상 가장 구체적인 예외 잡기
---
- 자바의 예외는 복잡한 타입 계층 구조를 가짐
- 예외를 잡으려면 **가장 구체적인 예외 타입을 잡아야 한다**
  - 왜냐하면, 일반적인 타입을 잡을 경우 잡아선 안될 오류까지 잡힐 위험이 있기 때문이다
  - 자바 유형에서 가장 일반적인 예외 유형인 Exception으로 예외를 처리하면
  - NullPointException처럼 **반드시 수정해야 할 코드 내 버그같이, 잡고 싶지 않은 예외 유형까지 잡게된다**
    > 참고) <br>
    > Exception의 상위 타입은 Throwable뿐 <br>
    > Throwable을 잡을 경우 OutOfMemoryError와 같은 가상 머신 내 오류까지 잡힐 수 있음

- 따라서 Exception 대신에 **try 코드 내에서 던질 만한 가장 구체적인 예외를 잡자**

- 자바7부터 다중 캐치 블록 등장

<br>

```java
//solution
class TransmissionParser {
    static Transmission parse(String rawMessage) {
        if (rawMessage != null &&
                rawMessage.length() != Transmission.MESSAGE_LENGTH) {
            throw new IllegalArgumentException("Bad message received!");
        }

        String rawId = rawMessage.substring(0, Transmission.ID_LENGTH);
        String rawContent = rawMessage.substring(Transmission.ID_LENGTH);
        try {
            int id = Integer.parseInt(rawId);
            String content = rawContent.trim();
            return new Transmission(id, content);
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException("Bad message received!");
        }
    }
}
```
- 예제에서 처리해야 할 구체적인 예외 유형은 NumberFormatException 하나 뿐
  - rawId에 Integer 클래스가 정숫값으로 변환할 수 없는 값이 들어있을 수 있음


<br>

### 5.3 메시지로 원인 설명
---
- 예외를 던질 때는 타입 규칙을 지켜야 예외를 좀 더 쉽게 처리할 수 있다
- 우리는 예외 타입을 보면 대강 무엇이 잘못되었는지 안다
- 하지만 예외 타입만으로 정보가 부족하다

- **예외 메시지로 자세한 원인을 설명하자**
  - **Expected [EXPECTED], but got [ACTUAL] in [CONTEXT]**
  - 바라는 것 / 받은 것 / 맥락 정보 제공

- 예외 메시지로 자세한 원인을 설명할 때 장점
  1. 예외의 근본적인 원인을 빨리 추척
  2. 예외를 일으킨 상황을 쉽게 재현
  3. 세 가지 정보를 테스트 케이스로 재사용 가능
     - JUnit 테스트로 변환해 버그 픽스를 만들고 이후 회귀 테스트로 사용

<br>

```java
// solution
class TransmissionParser {
    static Transmission parse(String rawMessage) {
        if (rawMessage != null
                && rawMessage.length() != Transmission.MESSAGE_LENGTH) {
            throw new IllegalArgumentException(
                String.format("Expected %d, but got %d characters in '%s'",
                    Transmission.MESSAGE_LENGTH, rawMessage.length(),
                    rawMessage));
        }

        String rawId = rawMessage.substring(0, Transmission.ID_LENGTH);
        String rawContent = rawMessage.substring(Transmission.ID_LENGTH);
        try {
            int id = Integer.parseInt(rawId);
            String content = rawContent.trim();
            return new Transmission(id, content);
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException(
                String.format("Expected number, but got '%s' in '%s'",
                        rawId, rawMessage));
        }
    }
}
```

<br>

### 5.4 원인 사슬 깨지 않기
---
- 예외는 또 다른 예외를 발생시킬 수 있다
  - 예외를 잡았지만 처리할 수 없다면 반드시 다시 던져야 한다
  - 예외에 버그가 있을 경우, 프로그램이 충돌할 때까지 전달될 수 있도록 !

- 오류를 제대로 처리했다면 **원인 사슬, 즉 각 예외가 그 예외를 일으킨 예외와 연결된 리스트를 보여주는 스택 추적을 확인할 수 있다**

- 버그를 추적할 때 원인 사슬이 자세하면 엄청난 도움이 된다

- 예외에는 다양한 생성자가 있고 그 중 원인으로 **Throwable을 전달하는 생성자를 사용함으로써 예외와 원인을 연관시키고 그로써 원인 사슬을 만들자**
  > Exception(String message, Throwable cause)

<br>

```java
// problem
String rawId = rawMessage.substring(0, Transmission.ID_LENGTH);
String rawContent = rawMessage.substring(Transmission.ID_LENGTH);
try {
    int id = Integer.parseInt(rawId);
    String content = rawContent.trim();
    return new Transmission(id, content);
} catch (NumberFormatException e) {
    throw new IllegalArgumentException(
        String.format("Expected number, but got '%s' in '%s'",
                        rawId, rawMessage));
}
```
  - 위 코드에서 문제점은 바로 원인인 NumberFormatException을 참조하지 않는 IllegalArgumentExcpetion
  - IllegalArgumentException의 스택 추적을 아무리 살펴보아도 NumberFormatException에서 비롯된 건지 아니면 어떤 코드 줄에서 발생했는지 힌트가 없음
  - NumberFormatException에는 추상화 수준을 달리해 더 많은 정보와 맥락을 제공하는 message와 줄 번호가 포함된 NumberFormatException 만의 스택 추적이 들어있음
  - 따라서 원인 사슬을 만드는 것이 필요!

<br>

```java
// solution
String rawId = rawMessage.substring(0, Transmission.ID_LENGTH);
String rawContent = rawMessage.substring(Transmission.ID_LENGTH);
try {
    int id = Integer.parseInt(rawId);
    String content = rawContent.trim();
    return new Transmission(id, content);
} catch (NumberFormatException e) {
    throw new IllegalArgumentException(
        String.format("Expected number, but got '%s' in '%s'",
                        rawId, rawMessage), e);
}
```

<br>

### 5.5 변수로 원인 노출
---
- **맞춤형 예외를 정의하고 사용하자**
  - 그 예외가 필요로 하는 필드를 정의해서 사용
  - 클래스와 그 필드를 final로 선언해 불변으로 만들기

- 이로써 예외 메시지가 일관되게 유지되며, 메시지 생성을 별도의 메서드로 추출하면 코드 중복도 제거된다

<br>

```java
// problem
class TransmissionParser {
    static Transmission parse(String rawMessage) {
        if (rawMessage != null
                && rawMessage.length() != Transmission.MESSAGE_LENGTH) {
            throw new IllegalArgumentException(
                String.format("Expected %d, but got %d characters in '%s'",
                    Transmission.MESSAGE_LENGTH, rawMessage.length(),
                    rawMessage));
        }

        String rawId = rawMessage.substring(0, Transmission.ID_LENGTH);
        String rawContent = rawMessage.substring(Transmission.ID_LENGTH);
        try {
            int id = Integer.parseInt(rawId);
            String content = rawContent.trim();
            return new Transmission(id, content);
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException(
                String.format("Expected number, but got '%s' in '%s'",
                    rawId, rawMessage), e);
        }
    }
}
```
- 위 코드에는 2가지 문제점이 존재
  1. 두 번이나 "in %s" 라는 방식으로 rawMessage를 넣음
     - 향후 sw 규모가 커지면 일관성을 잃기 쉬움
  2. 감추어진 정보
     - rawMessage를 예외 메시지에 인코딩
     - 나중에 rawMessage를 추출하고 싶을 때 힘듬

<br>

```java
// solution
final class MalformedMessageException extends IllegalArgumentException {

    final String raw;

    MalformedMessageException(String message, String raw) {
        super(String.format("%s in '%s'", message, raw));
        this.raw = raw;
    }

    MalformedMessageException(String message, String raw, Throwable cause) {
        super(String.format("%s in '%s'", message, raw), cause);
        this.raw = raw;
    }
}
```
```java
// soltuion
class TransmissionParser {
    static Transmission parse(String rawMessage) {
        if (rawMessage != null
                && rawMessage.length() != Transmission.MESSAGE_LENGTH) {
            throw new MalformedMessageException(
                String.format("Expected %d, but got %d characters",
                    Transmission.MESSAGE_LENGTH, rawMessage.length()),
                    rawMessage);
        }

        String rawId = rawMessage.substring(0, Transmission.ID_LENGTH);
        String rawContent = rawMessage.substring(Transmission.ID_LENGTH);
        try {
            int id = Integer.parseInt(rawId);
            String content = rawContent.trim();
            return new Transmission(id, content);
        } catch (NumberFormatException e) {
            throw new MalformedMessageException(
                String.format("Expected number, but got '%s'", rawId),
                rawMessage, e);
        }
    }
}
```

<br>

### 5.6 타입 변환 전에 항상 타입 검증하기
---
- 런타임에 동적 객체 타입을 처리해야 할 때가 있을 수 있다
  - 전형적으로 직렬화 된 자바 객체를 채널을 통해 주고받을 때
  - 명시적으로 어떤 타입으로든 변환해야 하는 경우
  - 적절히 변환하지 않으면 RuntimeException 예외 발생

- **프로그램이 외부와 상호작용할 때는 항상 예상하지 못한 입력을 처리할 수 있도록 대비**

```java
// problem
class Network {

    ObjectInputStream inputStream;
    InterCom interCom;

    void listen() throws IOException, ClassNotFoundException {
        while (true) {
            Object signal = inputStream.readObject();
            CrewMessage crewMessage = (CrewMessage) signal;
            interCom.broadcast(crewMessage);
        }
    }
}
```

```java
// soltuion
class Network {

    ObjectInputStream inputStream;
    InterCom interCom;

    void listen() throws IOException, ClassNotFoundException {
        while (true) {
            Object signal = inputStream.readObject();
            if (signal instanceof CrewMessage) {
              CrewMessage crewMessage = (CrewMessage) signal;
              interCom.broadcast(crewMessage);
            }
        }
    }
}
```

- ClassCastException을 피할 방법은 없으므로 다양한 타입으로 된 메시지를 받고 싶다면 instanceof로 차례대로 검증
- ClassNotFoundException은 개발 시에는 ClassCastException처럼 예외를 잡아 로깅

<br>


### 5.7 항상 자원 닫기
---

- 자원 누출 : 자원이 프로그램이 종료되기 전까지 해제되지 못하는 것

```java
// problem
class Logbook {

    static final Path LOG_FOLDER = Paths.get("/var/log");
    static final String FILE_FILTER = "*.log";

    List<Path> getLogs() throws IOException {
        List<Path> result = new ArrayList<>();

        DirectoryStream<Path> directoryStream =
                Files.newDirectoryStream(LOG_FOLDER, FILE_FILTER);
        for (Path logFile : directoryStream) {
            result.add(logFile);
        }
        directoryStream.close();

        return result;
    }
}
```
- 위 코드에서 close()로 해제 시 예외 발생하면 자원 누출 발생
- 어떻게 하면 자원을 **항상** 닫을 수 있을까?

<br>

```java
// solution
class Logbook {

    static final Path LOG_FOLDER = Paths.get("/var/log");
    static final String FILE_FILTER = "*.log";

    List<Path> getLogs() throws IOException {
        List<Path> result = new ArrayList<>();

        try (DirectoryStream<Path> directoryStream =
                     Files.newDirectoryStream(LOG_FOLDER, FILE_FILTER)) {
            for (Path logFile : directoryStream) {
                result.add(logFile);
            }
        }

        return result;
    }
}
```
- Java7부터는 **try-with-resource** 구문으로 자원을 안전하고 고상하게 닫자
- **try-with-resource**
  - AutoCloseable 인터페이스를 구현한 클래스여야 동작
  - 실제 자바 API 내 자원 클래스는 모두 이렇게 하고 있음
  - 단지 문법적으로 쓰기 편한 표현
  - 컴파일러가 아래와 같이 확장
    ```java
    DirectoryStream<Path> resource = Files.newDirectoryStream(LOG_FOLDER, FILE_FILTER);

    try {
      // 자원 사용
    } finally{
        if(resource != null) {
          resource.close();
        }
    }
    ```

<br>
